// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aliases.sql

package db

import (
	"context"
)

const countCharacterAliasMembers = `-- name: CountCharacterAliasMembers :one
SELECT COUNT(*) FROM character_alias_members
WHERE alias_id = ?
`

func (q *Queries) CountCharacterAliasMembers(ctx context.Context, aliasID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCharacterAliasMembers, aliasID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCharacterAlias = `-- name: DeleteCharacterAlias :exec
DELETE FROM character_aliases
WHERE id = ?
`

func (q *Queries) DeleteCharacterAlias(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCharacterAlias, id)
	return err
}

const deleteCharacterAliasMember = `-- name: DeleteCharacterAliasMember :exec
DELETE FROM character_alias_members
WHERE alias_id = ? AND character_id = ?
`

type DeleteCharacterAliasMemberParams struct {
	AliasID     int64 `json:"alias_id"`
	CharacterID int64 `json:"character_id"`
}

func (q *Queries) DeleteCharacterAliasMember(ctx context.Context, arg DeleteCharacterAliasMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteCharacterAliasMember, arg.AliasID, arg.CharacterID)
	return err
}

const deleteCharacterAliasMembers = `-- name: DeleteCharacterAliasMembers :exec
DELETE FROM character_alias_members
WHERE alias_id = ?
`

func (q *Queries) DeleteCharacterAliasMembers(ctx context.Context, aliasID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCharacterAliasMembers, aliasID)
	return err
}

const getCharacterAliasID = `-- name: GetCharacterAliasID :one
SELECT id FROM character_aliases
WHERE alias_name = ?
`

func (q *Queries) GetCharacterAliasID(ctx context.Context, aliasName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCharacterAliasID, aliasName)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCharacterAliasMember = `-- name: InsertCharacterAliasMember :exec
INSERT INTO character_alias_members(alias_id, character_id)
VALUES (?, ?)
ON CONFLICT(alias_id, character_id) DO NOTHING
`

type InsertCharacterAliasMemberParams struct {
	AliasID     int64 `json:"alias_id"`
	CharacterID int64 `json:"character_id"`
}

func (q *Queries) InsertCharacterAliasMember(ctx context.Context, arg InsertCharacterAliasMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertCharacterAliasMember, arg.AliasID, arg.CharacterID)
	return err
}

const listAliasCharacters = `-- name: ListAliasCharacters :many
SELECT c.region, c.realm, c.name, c.rio_score
FROM character_alias_members am
JOIN character_aliases a ON a.id = am.alias_id
JOIN characters c ON c.id = am.character_id
WHERE a.alias_name = ?
ORDER BY c.region, c.realm, c.name
`

type ListAliasCharactersRow struct {
	Region   string  `json:"region"`
	Realm    string  `json:"realm"`
	Name     string  `json:"name"`
	RioScore float64 `json:"rio_score"`
}

func (q *Queries) ListAliasCharacters(ctx context.Context, aliasName string) ([]ListAliasCharactersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAliasCharacters, aliasName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAliasCharactersRow
	for rows.Next() {
		var i ListAliasCharactersRow
		if err := rows.Scan(
			&i.Region,
			&i.Realm,
			&i.Name,
			&i.RioScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAliases = `-- name: ListAliases :many
SELECT alias_name
FROM character_aliases
ORDER BY alias_name
`

func (q *Queries) ListAliases(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var alias_name string
		if err := rows.Scan(&alias_name); err != nil {
			return nil, err
		}
		items = append(items, alias_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCharacterAlias = `-- name: UpsertCharacterAlias :one
INSERT INTO character_aliases(alias_name)
VALUES (?)
ON CONFLICT(alias_name) DO UPDATE SET alias_name = excluded.alias_name
RETURNING id
`

func (q *Queries) UpsertCharacterAlias(ctx context.Context, aliasName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertCharacterAlias, aliasName)
	var id int64
	err := row.Scan(&id)
	return id, err
}
