// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: elvui.sql

package db

import (
	"context"
)

const getElvUIVersion = `-- name: GetElvUIVersion :one
SELECT version, download_url, changelog_url, last_update, checked_at
FROM elvui_versions
WHERE id = 1
`

type GetElvUIVersionRow struct {
	Version      string `json:"version"`
	DownloadUrl  string `json:"download_url"`
	ChangelogUrl string `json:"changelog_url"`
	LastUpdate   string `json:"last_update"`
	CheckedAt    string `json:"checked_at"`
}

func (q *Queries) GetElvUIVersion(ctx context.Context) (GetElvUIVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getElvUIVersion)
	var i GetElvUIVersionRow
	err := row.Scan(
		&i.Version,
		&i.DownloadUrl,
		&i.ChangelogUrl,
		&i.LastUpdate,
		&i.CheckedAt,
	)
	return i, err
}

const upsertElvUIVersion = `-- name: UpsertElvUIVersion :exec
INSERT INTO elvui_versions (id, version, download_url, changelog_url, last_update)
VALUES (1, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  version = excluded.version,
  download_url = excluded.download_url,
  changelog_url = excluded.changelog_url,
  last_update = excluded.last_update,
  checked_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type UpsertElvUIVersionParams struct {
	Version      string `json:"version"`
	DownloadUrl  string `json:"download_url"`
	ChangelogUrl string `json:"changelog_url"`
	LastUpdate   string `json:"last_update"`
}

func (q *Queries) UpsertElvUIVersion(ctx context.Context, arg UpsertElvUIVersionParams) error {
	_, err := q.db.ExecContext(ctx, upsertElvUIVersion,
		arg.Version,
		arg.DownloadUrl,
		arg.ChangelogUrl,
		arg.LastUpdate,
	)
	return err
}
