// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_names.sql

package db

import (
	"context"
)

const getItemName = `-- name: GetItemName :one
SELECT name FROM item_names WHERE item_id = ?
`

func (q *Queries) GetItemName(ctx context.Context, itemID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getItemName, itemID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listItemNames = `-- name: ListItemNames :many
SELECT item_id, name, cached_at FROM item_names ORDER BY item_id
`

func (q *Queries) ListItemNames(ctx context.Context) ([]ItemName, error) {
	rows, err := q.db.QueryContext(ctx, listItemNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemName
	for rows.Next() {
		var i ItemName
		if err := rows.Scan(&i.ItemID, &i.Name, &i.CachedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItemName = `-- name: UpsertItemName :exec
INSERT INTO item_names (item_id, name)
VALUES (?, ?)
ON CONFLICT(item_id) DO UPDATE SET
  name = excluded.name,
  cached_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type UpsertItemNameParams struct {
	ItemID int64  `json:"item_id"`
	Name   string `json:"name"`
}

func (q *Queries) UpsertItemName(ctx context.Context, arg UpsertItemNameParams) error {
	_, err := q.db.ExecContext(ctx, upsertItemName, arg.ItemID, arg.Name)
	return err
}
