// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Character struct {
	ID       int64   `json:"id"`
	Region   string  `json:"region"`
	Realm    string  `json:"realm"`
	Name     string  `json:"name"`
	RioScore float64 `json:"rio_score"`
}

type CompletedKey struct {
	KeyID       int64  `json:"key_id"`
	CharacterID int64  `json:"character_id"`
	Dungeon     string `json:"dungeon"`
	KeyLvl      int64  `json:"key_lvl"`
	RunTimeMs   int64  `json:"run_time_ms"`
	ParTimeMs   int64  `json:"par_time_ms"`
	CompletedAt string `json:"completed_at"`
	Source      string `json:"source"`
	InsertedAt  string `json:"inserted_at"`
}

type ElvuiVersion struct {
	ID           int64  `json:"id"`
	Version      string `json:"version"`
	DownloadUrl  string `json:"download_url"`
	ChangelogUrl string `json:"changelog_url"`
	LastUpdate   string `json:"last_update"`
	CheckedAt    string `json:"checked_at"`
}

type WarcraftlogsLink struct {
	ID         int64          `json:"id"`
	KeyID      int64          `json:"key_id"`
	ReportCode string         `json:"report_code"`
	FightID    sql.NullInt64  `json:"fight_id"`
	PullID     sql.NullInt64  `json:"pull_id"`
	Url        sql.NullString `json:"url"`
	InsertedAt string         `json:"inserted_at"`
}
