// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountKeysByCharacterSince(ctx context.Context, completedAt string) ([]CountKeysByCharacterSinceRow, error)
	DeleteCharacter(ctx context.Context, id int64) error
	DeleteCompletedKeysByCharacter(ctx context.Context, characterID int64) error
	DeleteWarcraftLogsLinksByCharacter(ctx context.Context, id int64) error
	GetCharacter(ctx context.Context, arg GetCharacterParams) (Character, error)
	GetCharacterID(ctx context.Context, arg GetCharacterIDParams) (int64, error)
	InsertCompletedKey(ctx context.Context, arg InsertCompletedKeyParams) error
	InsertWarcraftLogsLink(ctx context.Context, arg InsertWarcraftLogsLinkParams) error
	ListAllKeysWithCharacters(ctx context.Context) ([]ListAllKeysWithCharactersRow, error)
	ListCharacters(ctx context.Context) ([]ListCharactersRow, error)
	ListKeysByCharacterSince(ctx context.Context, arg ListKeysByCharacterSinceParams) ([]ListKeysByCharacterSinceRow, error)
	ListKeysSince(ctx context.Context, completedAt string) ([]ListKeysSinceRow, error)
	ListWarcraftLogsLinksForKey(ctx context.Context, keyID int64) ([]ListWarcraftLogsLinksForKeyRow, error)
	UpsertCharacter(ctx context.Context, arg UpsertCharacterParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
