// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warcraftlogs.sql

package db

import (
	"context"
	"database/sql"
)

const insertWarcraftLogsLink = `-- name: InsertWarcraftLogsLink :exec
INSERT OR IGNORE INTO warcraftlogs_links(
  key_id, report_code, fight_id, pull_id, url
) VALUES (?, ?, ?, ?, ?)
`

type InsertWarcraftLogsLinkParams struct {
	KeyID      int64          `json:"key_id"`
	ReportCode string         `json:"report_code"`
	FightID    sql.NullInt64  `json:"fight_id"`
	PullID     sql.NullInt64  `json:"pull_id"`
	Url        sql.NullString `json:"url"`
}

func (q *Queries) InsertWarcraftLogsLink(ctx context.Context, arg InsertWarcraftLogsLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertWarcraftLogsLink,
		arg.KeyID,
		arg.ReportCode,
		arg.FightID,
		arg.PullID,
		arg.Url,
	)
	return err
}

const listWarcraftLogsLinksForKey = `-- name: ListWarcraftLogsLinksForKey :many
SELECT key_id, report_code, fight_id, pull_id, url, inserted_at
FROM warcraftlogs_links
WHERE key_id = ?
ORDER BY inserted_at DESC
`

type ListWarcraftLogsLinksForKeyRow struct {
	KeyID      int64          `json:"key_id"`
	ReportCode string         `json:"report_code"`
	FightID    sql.NullInt64  `json:"fight_id"`
	PullID     sql.NullInt64  `json:"pull_id"`
	Url        sql.NullString `json:"url"`
	InsertedAt string         `json:"inserted_at"`
}

func (q *Queries) ListWarcraftLogsLinksForKey(ctx context.Context, keyID int64) ([]ListWarcraftLogsLinksForKeyRow, error) {
	rows, err := q.db.QueryContext(ctx, listWarcraftLogsLinksForKey, keyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWarcraftLogsLinksForKeyRow
	for rows.Next() {
		var i ListWarcraftLogsLinksForKeyRow
		if err := rows.Scan(
			&i.KeyID,
			&i.ReportCode,
			&i.FightID,
			&i.PullID,
			&i.Url,
			&i.InsertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
